-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Users"
(
    id uuid NOT NULL,
    name character varying(255)[] NOT NULL,
    email character varying(255)[] NOT NULL,
    password character varying(255)[] NOT NULL,
    PRIMARY KEY (uuid)
);

CREATE TABLE IF NOT EXISTS public."Role"
(
    id integer NOT NULL,
    role_name character varying(255)[] NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Listings"
(
    id uuid NOT NULL,
    title character varying(255)[] NOT NULL,
    description text[],
    location character varying[] NOT NULL,
    price character varying[] NOT NULL,
    max_guests integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.photos
(
    id uuid NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Bookings"
(
    "Users_id" uuid NOT NULL,
    "Listings_id" uuid NOT NULL,
    starting_date date[] NOT NULL,
    ending_date date NOT NULL,
    total_cost integer NOT NULL
);

ALTER TABLE IF EXISTS public."Role"
    ADD FOREIGN KEY (id)
    REFERENCES public."Users" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Listings"
    ADD FOREIGN KEY (id)
    REFERENCES public."Users" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.photos
    ADD FOREIGN KEY (id)
    REFERENCES public."Listings" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Bookings"
    ADD FOREIGN KEY ("Users_id")
    REFERENCES public."Users" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Bookings"
    ADD FOREIGN KEY ("Listings_id")
    REFERENCES public."Listings" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;